services:
  grafana-otel:
    image: grafana/otel-lgtm:latest
    environment:
      - ENABLE_LOGS_TEMPO=true
      - ENABLE_LOGS_LOKI=true
    ports:
      - 3000:3000
      - 4318:4318
      - 4317:4317
